test\:get_next_line:
	$(call runtest,get_next_line,https://github.com/Tripouille/gnlTester.git,make)

test-n\:get_next_line:
	$(call runtest,get_next_line,https://github.com/Tripouille/gnlTester.git,make,1)