test\:printf:
	$(call runtest,printf,https://github.com/paulo-santana/ft_printf_tester.git,sh test $(arg))

test-n\:printf:
	$(call runtest,printf,https://github.com/paulo-santana/ft_printf_tester.git,sh test $(arg),1)


